### ISSUE TITLE
WoofBot app Umbrel PR

### ISSUE THREAD

**Issue by AaronDewes** [woofbotapp/woofbotapp#4]
Hi! I'm building @runcitadel, a FOSS Umbrel alternative. I'm planning to integrate WoofBot there. I got it running based on your Umbrel PR. Would you be okay with me adding @woofbotapp to @runcitadel, which is licensed under the GNU AGPL?

**Comment by woofbotapp** [comment]
Hi @AaronDewes , sorry for the late reply.
Yes, you can add woofbotapp version v0.2.0 to @runcitadel under the following conditions:
1. I am not familiar with the GNU AGPL license and cannot take responsibility for any dependencies that woofbotapp uses. You can see the dependencies here: https://github.com/woofbotapp/woofbotapp/blob/master/LICENSE-DEPENDENCIES and in the package.json files.
2. I reserve the right to revoke this permission for future versions of woofbotapp (above 0.2.0).
3. I do not permit to change the content of the sponsorship-message that is sent to the users,
which is currently: "Your sponsorship can be here! woofbot@protonmail.com" and may change in 
future versions of this software. The full condition is explained here: https://github.com/woofbotapp/woofbotapp/blob/master/LICENSE#L24-L38

Regarding future sponsorship, if such opportunity occurs, please contact me at woofbot@protonmail.com and we can discuss your commission as the "App Store" distributer.

Please also remind the users that this is an early beta version, and should be considered unsafe.

Regards,
WoofBotApp

**Comment by AaronDewes** [comment]
Thank you for your reply! The AGPL is incompatible with your license, but because we simply download the Woofbot container, we can include Woofbot easily and there is no license issue (because Woofbot is completely separate from Citadel, like on Umbrel).

> I reserve the right to revoke this permission for future versions of woofbotapp (above 0.2.0).

We normally update apps automatically based on new releases in their GitHub release, so if you want to revoke this permission, please let me know at aaron@runcitadel.space so I can revert to an older version.

**Comment by woofbotapp** [comment]
Agreed. I will contact you if there will be reasons for me to not allow updates of future versions. Have a nice day!
